apiVersion: v1
kind: ConfigMap
data:
  target-namespace: default
  target-service: echoheaders
  vip: 10.10.40.44
metadata:
  labels:
    loadbalancer: barematel
  name: vip-echoserver
  namespace: default

